fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.13.1"

# profile module layout, default include ntp module
    ntp:
      repo: "https://github.com/puppetlabs/puppetlabs-ntp.git"
      ref: "4.2.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      branch: "1.2.x"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    puppet-staging: "https://github.com/voxpupuli/puppet-staging.git"
    epel: "https://github.com/stahnma/puppet-module-epel.git"

  symlinks:
    profile_lamp: "#{source_dir}"
